Download SET history price

In [1]:
# import library
import pandas as pd
import numpy as np
from tqdm import tqdm
import yfinance as yf

import warnings
warnings.filterwarnings('ignore')

# import date library
from datetime import date
today = date.today().strftime("%m_%d_%y")

print('pandas v.',pd.__version__,
      '\numpy v.',np.__version__,
      '\nyfinace v.',yf.__version__)

pandas v. 1.5.2
umpy v. 1.23.5
yfinace v. 0.2.12

In [5]:
# read SET symbol
df_symbol = pd.read_csv('Symbol_SET.csv')
tickers = df_symbol[df_symbol['Symbol'].str.contains('-R.BK') == False].reset_index(drop=True)
tickers.head()

In [6]:
# download history function
def download_history(ticker = 'ADVANC.BK',period='1y',interval='1d'):
    """
    ticker: equity symbol in yahoo finance
    periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max (time period)
    interval: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo (trading interval)
    fetch data by interval (including intraday if period < 60 days)
    """
    data = yf.download(tickers = ticker, period = period, interval = interval)
    data['Symbol'] = ticker

    return data

In [8]:
download_history()

[*********************100%***********************]  1 of 1 completed

             Open   High    Low  Close   Adj Close   Volume     Symbol
Date
2022-06-09  211.0  213.0  210.0  212.0  204.136459  5267000  ADVANC.BK
2022-06-10  211.0  211.0  207.0  208.0  200.284821  6371100  ADVANC.BK
2022-06-13  206.0  208.0  205.0  207.0  199.321915  5286400  ADVANC.BK
2022-06-14  206.0  210.0  205.0  209.0  201.247726  3995600  ADVANC.BK
2022-06-15  208.0  208.0  206.0  206.0  198.359009  3916600  ADVANC.BK
...           ...    ...    ...    ...         ...      ...        ...
2023-06-02  210.0  213.0  208.0  212.0  212.000000  3373100  ADVANC.BK
2023-06-06  214.0  214.0  211.0  214.0  214.000000  3530200  ADVANC.BK
2023-06-07  215.0  215.0  213.0  215.0  215.000000  3611500  ADVANC.BK
2023-06-08  215.0  218.0  214.0  217.0  217.000000  4091500  ADVANC.BK
2023-06-09  217.0  219.0  217.0  219.0  219.000000  5769888  ADVANC.BK

[244 rows x 7 columns]

In [7]:
# define period and interval 

# valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
period = 'max'

# fetch data by interval including intraday if period < 60 days)
# valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
intervals = ['1d','1wk']

for interval in intervals:
    df = pd.DataFrame()
    for ticker in tqdm(tickers['Symbol'][:]):
        # print(ticker)
        df_temp = download_history(ticker,period,interval)
        df = pd.concat([df,df_temp])

    print(df.head())
    print(df.tail())

    # save df to parquet file
    df.to_parquet(f'SET_history_price_{interval}_{today}.gzip',compression='gzip')

TypeError: list indices must be integers or slices, not str